import { Product } from "./types"

export const initialProducts: Product[] = [
  {
    id: "livlik-ds",
    name: "LIVLIK-DS",
    subtitle: "SYRUP",
    hindi: "लिवलिक सीरप",
    tagline: "Comprehensive Liver Health Formula",
    description:
      "Effective in Fatty Liver. A comprehensive ayurvedic formulation supporting optimal liver function, detoxification, and hepatic health.",
    size: "500 ml",
    mrp: 699,
    costPrice: 350,
    markup: 25,
    sellingPrice: 699,
    category: "Liver Health",
    color: "#f5e642",
    accentColor: "#1a5c2e",
    batchNo: "MP 302",
    mfgDate: "JUN-29",
    expiry: "3 Yrs. from mfg.",
    licNo: "A-4309/2011",
    composition: [
      { herb: "Tephrosia Purpurea", qty: "1000 mg" },
      { herb: "Eclipta alba", qty: "900 mg" },
      { herb: "Cichorium Intybus", qty: "1100 mg" },
      { herb: "Foeniculum vulgare", qty: "1000 mg" },
      { herb: "Terminalia Chebula", qty: "800 mg" },
      { herb: "Piper longum", qty: "500 mg" },
      { herb: "Tinospora cordifolia", qty: "1200 mg" },
      { herb: "Solamum nigrum", qty: "1200 mg" },
      { herb: "Cyperus rotundus", qty: "1100 mg" },
      { herb: "Fumaria Indica", qty: "1000 mg" },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "leukolik",
    name: "LEUKOLIK",
    subtitle: "SYRUP",
    hindi: "लियोकोलिक सीरप",
    tagline: "Women's Health & Wellness Tonic",
    description:
      "For All Age Groups. A carefully crafted ayurvedic blend supporting women's reproductive health and overall wellness.",
    size: "500 ml",
    mrp: 449,
    costPrice: 200,
    markup: 30,
    sellingPrice: 449,
    category: "Women's Health",
    color: "#f7a8c4",
    accentColor: "#c0399a",
    batchNo: "MP 306",
    mfgDate: "JUN-29",
    expiry: "3 Yrs. from mfg.",
    licNo: "A-4309/2011",
    composition: [
      { herb: "Saraca indica", qty: "600 mg" },
      { herb: "Sida cordifolia", qty: "550 mg" },
      { herb: "Symploeos racemosus", qty: "550 mg" },
      { herb: "Punica granatum", qty: "400 mg" },
      { herb: "Embica officianalis", qty: "500 mg" },
      { herb: "Terminalia chebula", qty: "450 mg" },
      { herb: "Terminalia belerica", qty: "450 mg" },
      { herb: "Cuminum cyminum", qty: "500 mg" },
      { herb: "Acacia arabica", qty: "600 mg" },
      { herb: "Cyperus rostundus", qty: "400 mg" },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "zimlik",
    name: "ZIMLIK",
    subtitle: "SYRUP",
    hindi: "जिमलिक सीरप",
    tagline: "Comprehensive Immunity Booster Formula & General Health",
    description:
      "A powerful blend of immunity-enhancing herbs for robust general health and vitality.",
    size: "500 ml",
    mrp: 649,
    costPrice: 300,
    markup: 28,
    sellingPrice: 649,
    category: "Immunity",
    color: "#b8d4f5",
    accentColor: "#2563eb",
    batchNo: "MP 303",
    mfgDate: "JUN-29",
    expiry: "3 Yrs. from mfg.",
    licNo: "A-4309/2011",
    composition: [
      { herb: "Apium graveolens", qty: "500 mg" },
      { herb: "Carum copticum", qty: "500 mg" },
      { herb: "Piper longum", qty: "400 mg" },
      { herb: "Mentha spicata", qty: "500 mg" },
      { herb: "Foenticulum vulgare", qty: "600 mg" },
      { herb: "Aloe Vera", qty: "600 mg" },
      { herb: "Zingiber officianale", qty: "400 mg" },
      { herb: "Piper nigrum", qty: "500 mg" },
      { herb: "Terminalia chebula", qty: "500 mg" },
      { herb: "Cuminum eyminum", qty: "500 mg" },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "urolik",
    name: "UROLIK",
    subtitle: "SYRUP",
    hindi: "यूरोलिक सीरप",
    tagline: "Powerfull Tonic For Kidney Health",
    description:
      "For All Age Groups. A potent ayurvedic formulation that supports kidney function, urinary health, and renal detoxification.",
    size: "500 ml",
    mrp: 999,
    costPrice: 480,
    markup: 20,
    sellingPrice: 999,
    category: "Kidney Health",
    color: "#c3f5c3",
    accentColor: "#1a5c2e",
    batchNo: "MP 305",
    mfgDate: "JUN-29",
    expiry: "3 Yrs. from mfg.",
    licNo: "A-4309/2011",
    composition: [
      { herb: "Boerhavia Diffusa", qty: "600 mg" },
      { herb: "Tribulus Terrestris", qty: "550 mg" },
      { herb: "Bergenia Ligutatia", qty: "500 mg" },
      { herb: "Crataeva Nrvala", qty: "550 mg" },
      { herb: "Achyranthes Aspera", qty: "400 mg" },
      { herb: "Cichorium Intybus", qty: "450 mg" },
      { herb: "Cumimum Cymimum", qty: "450 mg" },
      { herb: "Sida Cordifolia", qty: "500 mg" },
      { herb: "Fumaria Indica", qty: "400 mg" },
      { herb: "Butea monospermosa", qty: "600 mg" },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "dermolik",
    name: "DERMOLIK",
    subtitle: "SYRUP",
    hindi: "ड्मोलिक सीरप",
    tagline: "Comprehensive Skin Health & Chronic Psoriasis Formula",
    description:
      "A targeted ayurvedic blend for skin disorders, psoriasis management, and overall dermatological wellness.",
    size: "500 ml",
    mrp: 1100,
    costPrice: 550,
    markup: 22,
    sellingPrice: 1100,
    category: "Skin Health",
    color: "#e8d5f5",
    accentColor: "#7c3aed",
    batchNo: "MP 301",
    mfgDate: "JUN-29",
    expiry: "3 Yrs. from mfg.",
    licNo: "A-4309/2011",
    composition: [
      { herb: "Acacia catechu", qty: "550 mg" },
      { herb: "Tinospora cordifolia", qty: "500 mg" },
      { herb: "Rubia cordifolia", qty: "500 mg" },
      { herb: "Vetivenia zizanioides", qty: "600 mg" },
      { herb: "Plumbagozeylanica", qty: "450 mg" },
      { herb: "Fumaria indica", qty: "500 mg" },
      { herb: "Eclipta alba", qty: "450 mg" },
      { herb: "Tephrosia purpurea", qty: "500 mg" },
      { herb: "Terminalia chebula", qty: "450 mg" },
      { herb: "Cassia fistula", qty: "550 mg" },
    ],
    inStock: true,
    featured: false,
  },
  {
    id: "barentolik",
    name: "BARENTOLIK",
    subtitle: "SYRUP",
    hindi: "ब्रेनटोलिक सीरप",
    tagline: "Powerful Memory Enhancer & Brain Tonic",
    description:
      "A synergistic blend of traditional brahmi herbs and adaptogens to enhance memory, focus, and cognitive vitality.",
    size: "500 ml",
    mrp: 899,
    costPrice: 420,
    markup: 24,
    sellingPrice: 899,
    category: "Brain Health",
    color: "#d5c3f5",
    accentColor: "#5b21b6",
    batchNo: "MP 304",
    mfgDate: "JUN-29",
    expiry: "3 Yrs. from mfg.",
    licNo: "A-4309/2011",
    composition: [
      { herb: "Jatamasi", qty: "50 mg" },
      { herb: "Tagar", qty: "50 mg" },
      { herb: "Kusht Mand", qty: "50 mg" },
      { herb: "Gajwa", qty: "50 mg" },
      { herb: "Pipal Badi", qty: "50 mg" },
      { herb: "Aloe Vera", qty: "600 mg" },
      { herb: "Ashwagandha", qty: "45 mg" },
      { herb: "Amla", qty: "50 mg" },
      { herb: "Haritki", qty: "50 mg" },
      { herb: "Mandap Pushpi", qty: "50 mg" },
    ],
    inStock: true,
    featured: false,
  },
]
